//------------------------------------------------------------------------------
// <auto-generated>
//      Цей код створено програмним засобом.
//      Зміни в цьому файлі можуть призвести до неправильної поведінки і будуть втрачені,
//      якщо код створено повторно.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data_Analysis.Properties
{
    /// <summary>
    ///   Клас ресурсів зі строгим типом для пошуку локалізованих рядків та ін.
    /// </summary>
    // Цей клас був автоматично створений за допомогою StronglyTypedResourceBuilder
    // клас за допомогою таких засобів, як ResGen або Visual Studio.
    // Щоб додати або видалити член, змініть файл .ResX, а потім перезапустіть ResGen
    // з параметром /str або знову побудуйте свій VS-проект.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources
    {
        private static global::System.Resources.ResourceManager resourceMan;
        private static global::System.Globalization.CultureInfo resourceCulture;
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() { }

        /// <summary>
        ///   Повернення кешованого екземпляра ResourceManager, що використовується цим класом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if ((resourceMan == null))
                {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Data_Analysis.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Перевизначає властивість CurrentUICulture поточного потоку для всіх
        ///   підстановок ресурсів за допомогою цього класу ресурсів зі строгим типом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture
        {
            get { return resourceCulture; }
            set { resourceCulture = value; }
        }
    }
}