//------------------------------------------------------------------------------
// <auto-generated>
//     Цей код був створений за допомогою інструмента.
//     Зміни до цього файлу можуть мати неправильну поведінку та буде втрачено, якщо
//     код буде змінено.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data_Analysis.Properties
{
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "11.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase
    {
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        public static Settings Default
        {
            get { return defaultInstance; }
        }
    }
}